publish:
  docker:
    repo: registry.gruppenrat:5000/postfix-dbmail
    file: postfix-dbmail/Dockerfile
    insecure: true
    tag: latest
    registry: registry.gruppenrat:5000

publish:
  docker:
    repo: registry.gruppenrat:5000/php-fpm
    file: php-fpm/Dockerfile
    insecure: true
    tag: latest
    registry: registry.gruppenrat:5000

publish:
  docker:
    repo: registry.gruppenrat:5000/caddy
    file: caddy/Dockerfile
    insecure: true
    tag: latest
    registry: registry.gruppenrat:5000

notify:
  webhook:
    urls:
      - http://webhook.gruppenrat:3142/drone

